Repository vmware/vic-product, pull requests merged in 2018-09, with the labels that each got.

#2003 Remove page link to install vSphere client plugin
  installer/fileserver/html/index.html
Labels: cla-not-required

#2010 Repository description
  docs/user_doc/vic_cloud_admin/manage_repository_registry.md
Labels: cla-not-required

#2009 Cherry-pick: Remove page link to install vSphere client plugin (#2003)
  installer/fileserver/html/index.html
Labels: cla-not-required

#1923 Fix the certs is signed by nil when FQDN is specified for vic-ip
  dinv/build.sh
  dinv/certs.go
  dinv/ci.sh
  dinv/dch-photon-1.12/Dockerfile
  dinv/dch-photon-1.12/main.go
  dinv/dch-photon-1.13/Dockerfile
  dinv/dch-photon-1.13/certs.go
  dinv/dch-photon-17.06/Dockerfile
  dinv/dch-photon-17.06/certs.go
  dinv/dch-photon-17.06/main.go
  dinv/main.go
  dinv/vic_ip.go
  tests/test-cases/Group5-DCH/5-01-DCH.robot
Labels: cla-not-required

#2017 Quote potentially empty param to nimbus keyword
  tests/manual-test-cases/Group5-Interoperability-Tests/5-05-Enhanced-Linked-Mode.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-06-2-VSAN-Complex.disabled
  tests/manual-test-cases/Group5-Interoperability-Tests/5-09-Network-Folder.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-16-vMotion-VCH-Appliance.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-17-FC-Datastore.robot
  tests/resources/Nimbus-Util.robot
  tests/resources/nimbus-testbeds/ELM-DRS-Disabled.robot
Labels: cla-not-required, component/test/scenario

#2022 Remove specifying nimbus location
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#2024 Change vic ui version string to remove prefix
  installer/build/scripts/provisioners/provision_fileserver.sh
Labels: cla-not-required

#1984 Updates-#1774-Simplify log collection directions. Converted bullets t…
  docs/user_doc/vic_vsphere_admin/log_bundles.md
Labels: cla-not-required

#2016 Cherry-pick: Fixing 5-06-1-VSAN-Simple failures (#2001)
  tests/manual-test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.robot
  tests/resources/OVA-Util.robot
  tests/resources/VC-Util.robot
  tests/resources/VIC-UI-Util.robot
Labels: cla-not-required

#2004 Fix OVA initialization UI test
  installer/fileserver/html/index.html
  installer/fileserver/html/js/index-handler.js
  installer/fileserver/tasks/plugin.go
  tests/resources/page-objects/Complete-Installation-Modal-Util.robot
  tests/resources/page-objects/Getting-Started-Page-Util.robot
  tests/test-cases/Group2-Getting-Started/2-01-Getting-Started.robot
Labels: cla-not-required

#2032 read me document will open another tab page
  installer/fileserver/html/index.html
Labels: cla-not-required

#2031 Fix OVA initialization UI test (#2004)
  installer/fileserver/html/index.html
  installer/fileserver/html/js/index-handler.js
  installer/fileserver/tasks/plugin.go
  tests/resources/page-objects/Complete-Installation-Modal-Util.robot
  tests/resources/page-objects/Getting-Started-Page-Util.robot
  tests/test-cases/Group2-Getting-Started/2-01-Getting-Started.robot
Labels: cla-not-required

#2030 Added thumbprint value to json payload
  docs/user_doc/vic_vsphere_admin/ova_reg_api.md
Labels: cla-not-required

#2034 Remove vic_ui*.tar.gz from fileserver
  installer/build/scripts/provisioners/provision_fileserver.sh
Labels: cla-not-required

#2035 [Cherry-pick]Fix wrong TEST_RESOURCE path for 2-05-Static-IP (#1993)
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#2036 Cherry-pick: Remove vic_ui*.tar.gz from fileserver (#2034)
  installer/build/scripts/provisioners/provision_fileserver.sh
Labels: cla-not-required

#2025 Cherry-Pick: Remove specifying nimbus location (#2022)
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#1994 Cherry-pick: Improve and deduplicate slack notifications (#1983)
  .drone.yml
Labels: cla-not-required

#2038 Adding the source files for the networking and roles graphics
  docs/user_doc/graphic_sources/VIC_Networking.ai
  docs/user_doc/graphic_sources/VIC_conceptual_overview.ai
Labels: cla-not-required

#2014 Update document to reflect vic ui build change
  installer/docs/BUILD.md
  installer/docs/RELEASE.md
Labels: cla-not-required

#2044 Moved topic from users back to app_dev to fix link in Getting Started page
  docs/user_doc/SUMMARY.md
  docs/user_doc/vic_app_dev/run_dev_project.md
  docs/user_doc/vic_users/SUMMARY.md
Labels: cla-not-required

#2019 Added troubleshooting topic for appliance welcome page error
  docs/user_doc/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/vicappliance_welcomepage_error.md
Labels: cla-not-required

#2039 Appliancelogscript
  docs/user_doc/vic_vsphere_admin/appliance_logs.md
Labels: cla-not-required

#2042 Added that vCenter Server HA is not supported
  docs/user_doc/vic_vsphere_admin/interop.md
Labels: cla-not-required

#2055 Updating to v1.4.3 license
  installer/fileserver/files/open_source_license.txt
Labels: cla-not-required

#2053 Fix quoting of registration payload in upgrade.sh
  installer/build/scripts/upgrade/upgrade.sh
Labels: cla-not-required

#2054 Simplify upgrade.sh input for manual disk move
  installer/build/scripts/upgrade/upgrade.sh
Labels: cla-not-required

#2056 Cherry-pick:Updating to v1.4.3 license (#2055)
  installer/fileserver/files/open_source_license.txt
Labels: cla-not-required

#2058 Simplify upgrade.sh input for manual disk move (#2054)
  installer/build/scripts/upgrade/upgrade.sh
Labels: cla-not-required

#2012 Documented automatic plug-in installation and upgrade
  docs/user_doc/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/access_vicadmin.md
  docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md
  docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
  docs/user_doc/vic_vsphere_admin/install_vic_plugin.md
  docs/user_doc/vic_vsphere_admin/installing_vic.md
  docs/user_doc/vic_vsphere_admin/plugin_verify_deployment.md
  docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
  docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
  docs/user_doc/vic_vsphere_admin/restart_services.md
  docs/user_doc/vic_vsphere_admin/security_reference.md
  docs/user_doc/vic_vsphere_admin/service_status.md
  docs/user_doc/vic_vsphere_admin/ts_install_plugins.md
  docs/user_doc/vic_vsphere_admin/ts_ovf_error.md
  docs/user_doc/vic_vsphere_admin/ts_plugin_script_fails.md
  docs/user_doc/vic_vsphere_admin/ts_ui_not_appearing.md
  docs/user_doc/vic_vsphere_admin/uninstall_vic.md
  docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
  docs/user_doc/vic_vsphere_admin/upgrade_appliance_manual.md
  docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md
  docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_windows.md
  docs/user_doc/vic_vsphere_admin/upgrade_plugins.md
  docs/user_doc/vic_vsphere_admin/upgrade_vch.md
  docs/user_doc/vic_vsphere_admin/upgrading_vic.md
  docs/user_doc/vic_vsphere_admin/vch_admin_client.md
  docs/user_doc/vic_vsphere_admin/vch_portlet_ui.md
  docs/user_doc/vic_vsphere_admin/vic_engine_bundle.md
  docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md
Labels: cla-not-required

#2045 Documented vic-machine autocomplete
  docs/user_doc/vic_vsphere_admin/running_vicmachine_cmds.md
Labels: cla-not-required

#2052 Added --no-proxy option to docs
  docs/user_doc/vic_vsphere_admin/vch_proxy.md
  docs/user_doc/vic_vsphere_admin/vicmachine_options_ref.md
Labels: cla-not-required

#2061 Added line to network protocols diagram
  docs/user_doc/graphic_sources/Network-protocols.ai
  docs/user_doc/vic_vsphere_admin/graphics/Network-protocols.png
Labels: cla-not-required

#2060 Update document to reflect vic ui build change (#2014)
  installer/docs/BUILD.md
  installer/docs/RELEASE.md
Labels: cla-not-required

#2048 Add upgrade-ui-plugin option to nightly test
  installer/build/scripts/upgrade/upgrade.sh
  tests/resources/OVA-Util.robot
Labels: cla-not-required

#2069 Cherry-pick: Add upgrade-ui-plugin option to nightly test (#2048)
  installer/build/scripts/upgrade/upgrade.sh
  tests/resources/OVA-Util.robot
Labels: cla-not-required

#2020 Added topic on multiple appliance deployment topologies
  docs/user_doc/SUMMARY.md
  docs/user_doc/vic_overview/SUMMARY.md
  docs/user_doc/vic_overview/vic_deployment_topos.md
  docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
Labels: cla-not-required

#2068 Corrected appliance certificate location
  docs/user_doc/SUMMARY.md
  docs/user_doc/vic_cloud_admin/SUMMARY.md
  docs/user_doc/vic_cloud_admin/logging_in_MP.md
  docs/user_doc/vic_cloud_admin/trust_vic_certs.md
  docs/user_doc/vic_vsphere_admin/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
  docs/user_doc/vic_vsphere_admin/obtain_appliance_certs.md
  docs/user_doc/vic_vsphere_admin/ts_cert_error.md
  docs/user_doc/vic_vsphere_admin/vic_cert_reference.md
Labels: cla-not-required

#2041 Fix Group9-VIC-UI test failure
  tests/manual-test-cases/Group9-VIC-UI/9-2-VIC-UI-Uninstaller.robot
Labels: cla-not-required

#2070 Fixing failure in 5-16-vMotion-VCH-Appliance
  tests/manual-test-cases/Group5-Interoperability-Tests/5-16-vMotion-VCH-Appliance.robot
Labels: cla-not-required

#2091 Add missing external psc information into register
  installer/fileserver/routes/register.go
Labels: cla-not-required

#2092 Cherry-pick: Add missing external psc information into register (#2091)
  installer/fileserver/routes/register.go
Labels: cla-not-required

#2005 Sizing guidelines
  docs/user_doc/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/deploy_vch.md
  docs/user_doc/vic_vsphere_admin/ts_deploy_vch.md
  docs/user_doc/vic_vsphere_admin/ts_vch_incorrect_initialization.md
  docs/user_doc/vic_vsphere_admin/vch_sizing_guidelines.md
Labels: cla-not-required

#2089 Added step to restart client after removing plug-in
  docs/user_doc/vic_vsphere_admin/ts_ui_not_appearing.md
  docs/user_doc/vic_vsphere_admin/uninstall_vic.md
Labels: cla-not-required

#2093 Documented reinitialization for client install/upgrade and PSC update
  docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
  docs/user_doc/vic_vsphere_admin/reinitialize_appliance.md
Labels: cla-not-required

#2095 Small last minute fixes
  docs/user_doc/SUMMARY.md
  docs/user_doc/vic_overview/intro_to_vic.md
  docs/user_doc/vic_overview/intro_to_vic_mp.md
  docs/user_doc/vic_overview/intro_to_vic_registry.md
  docs/user_doc/vic_vsphere_admin/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/mgmt_network.md
Labels: cla-not-required

#2097 Corrected IP range for bridge network
  docs/user_doc/vic_vsphere_admin/bridge_network.md
Labels: area/pub, cla-not-required

#2102 Worked on Dani's comments on live logs
  docs/user_doc/vic_vsphere_admin/log_bundles.md
Labels: cla-not-required

#2105 Included information on vra 7.5
  docs/user_doc/vic_vsphere_admin/interop.md
Labels: cla-not-required
