Repository vmware/vic-product, pull requests merged in 2018-12, with the labels that each got.

#2191 Update upgrade-harbor.sh
  installer/build/scripts/upgrade/upgrade-harbor.sh
Labels: cla-not-required

#2183 Enable collecting Appliance and VCH log
  tests/manual-test-cases/Disabled-tests.robot
  tests/manual-test-cases/Group2-OVA-Features/2-05-Static-IP.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-01-Distributed-Switch-No-Cluster.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-03-Multiple-Datacenter.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-04-Multiple-Cluster.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-05-Enhanced-Linked-Mode.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-08-DRS.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-09-Network-Folder.robot
  tests/manual-test-cases/Group6-OVA-TLS/6-01-OVA-TLS.robot
  tests/manual-test-cases/Group7-Upgrade/7-01-Upgrade-1.2.1.robot
  tests/manual-test-cases/Group7-Upgrade/7-02-Upgrade-1.3.0.robot
  tests/manual-test-cases/Group7-Upgrade/7-03-Upgrade-1.3.1.robot
  tests/manual-test-cases/Group7-Upgrade/7-04-Upgrade-1.4.0.robot
  tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.2.1.robot
  tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.3.0.robot
  tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.3.1.robot
  tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.4.0.robot
  tests/manual-test-cases/Group9-VIC-UI/9-1-VIC-UI-Installer.robot
  tests/manual-test-cases/Group9-VIC-UI/9-2-VIC-UI-Uninstaller.robot
  tests/resources/OVA-Util.robot
  tests/resources/VCH-Util.robot
  tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot
Labels: cla-not-required

#2182 Removed instruction not to manually restart VCH
  docs/user_doc/vic_vsphere_admin/interop.md
Labels: cla-not-required

#2200 Add https:// when setting VIC-ADMIN variable
  tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot
Labels: cla-not-required

#2201 Pointing the edit button to 1.4 docs
  docs/user_doc/book.json
Labels: cla-not-required

#2202 Website
  package-lock.json
  src/app/app.component.html
Labels: cla-not-required

#2206 Updating version/year for 1.5, removing plug-in docs
  docs/user_doc/README.md
  docs/user_doc/SUMMARY.md
  docs/user_doc/book.json
  docs/user_doc/covers/vic_app_dev_cover.pub
  docs/user_doc/covers/vic_cloud_admin_cover.pub
  docs/user_doc/covers/vic_overview_cover.pub
  docs/user_doc/covers/vic_users_cover.pub
  docs/user_doc/covers/vic_vsphere_admin_cover.pub
  docs/user_doc/pdf.md
  docs/user_doc/vic_app_dev/README.md
  docs/user_doc/vic_app_dev/book.json
  docs/user_doc/vic_app_dev/configure_docker_client.md
  docs/user_doc/vic_app_dev/container_operations.md
  docs/user_doc/vic_app_dev/cover.jpg
  docs/user_doc/vic_app_dev/docker_compose_file_options.md
  docs/user_doc/vic_app_dev/dockerfile_support.md
  docs/user_doc/vic_cloud_admin/README.md
  docs/user_doc/vic_cloud_admin/add_project_registry.md
  docs/user_doc/vic_cloud_admin/book.json
  docs/user_doc/vic_cloud_admin/cover.jpg
  docs/user_doc/vic_cloud_admin/working_with_registries.md
  docs/user_doc/vic_overview/README.md
  docs/user_doc/vic_overview/book.json
  docs/user_doc/vic_overview/cover.jpg
  docs/user_doc/vic_users/README.md
  docs/user_doc/vic_users/cover.jpg
  docs/user_doc/vic_vsphere_admin/README.md
  docs/user_doc/vic_vsphere_admin/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/access_h5_ui.md
  docs/user_doc/vic_vsphere_admin/access_vicadmin.md
  docs/user_doc/vic_vsphere_admin/book.json
  docs/user_doc/vic_vsphere_admin/configure_vch.md
  docs/user_doc/vic_vsphere_admin/cover.jpg
  docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md
  docs/user_doc/vic_vsphere_admin/deploy_vch_esxi.md
  docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
  docs/user_doc/vic_vsphere_admin/install_vic_plugin.md
  docs/user_doc/vic_vsphere_admin/installing_vic.md
  docs/user_doc/vic_vsphere_admin/mgmt_network.md
  docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
  docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
  docs/user_doc/vic_vsphere_admin/reinitialize_appliance.md
  docs/user_doc/vic_vsphere_admin/running_vicmachine_cmds.md
  docs/user_doc/vic_vsphere_admin/ts_appliance_initialization_errors.md
  docs/user_doc/vic_vsphere_admin/ts_install_plugins.md
  docs/user_doc/vic_vsphere_admin/ts_plugin_script_fails.md
  docs/user_doc/vic_vsphere_admin/ts_ui_not_appearing.md
  docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
  docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md
  docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_windows.md
  docs/user_doc/vic_vsphere_admin/upgrade_plugins.md
  docs/user_doc/vic_vsphere_admin/upgrading_vic.md
  docs/user_doc/vic_vsphere_admin/vch_compute.md
  docs/user_doc/vic_vsphere_admin/vch_portlet_ui.md
  docs/user_doc/vic_vsphere_admin/vch_proxy.md
  docs/user_doc/vic_vsphere_admin/vic_engine_bundle.md
  docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md
Labels: cla-not-required

#1989 WIP: Updates to the dch-photon docs
  docs/user_doc/SUMMARY.md
  docs/user_doc/favicon.ico
  docs/user_doc/vic_app_dev/SUMMARY.md
  docs/user_doc/vic_app_dev/add_custom_ca.md
  docs/user_doc/vic_app_dev/build_push_images.md
  docs/user_doc/vic_app_dev/container_operations.md
  docs/user_doc/vic_app_dev/dch_advanced.md
  docs/user_doc/vic_app_dev/dch_expand_disk.md
  docs/user_doc/vic_app_dev/dch_photon_proxy.md
  docs/user_doc/vic_app_dev/dchphoton_options.md
  docs/user_doc/vic_app_dev/deploy_multiple_docker_compose.md
  docs/user_doc/vic_app_dev/deploy_single_containervm.md
  docs/user_doc/vic_app_dev/deploy_test_dch.md
  docs/user_doc/vic_app_dev/network_use_cases.md
  docs/user_doc/vic_app_dev/photon_cert_custom.md
  docs/user_doc/vic_app_dev/photon_cert_manual.md
  docs/user_doc/vic_app_dev/putting_apps_into_production.md
  docs/user_doc/vic_app_dev/test_photon.md
  docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md
  docs/user_doc/vic_vsphere_admin/vicadmin_status_ref.md
Labels: area/pub, cla-not-required

#2209 Merging dch-photon updates into 1.4-docs branch
  docs/user_doc/SUMMARY.md
  docs/user_doc/favicon.ico
  docs/user_doc/vic_app_dev/SUMMARY.md
  docs/user_doc/vic_app_dev/add_custom_ca.md
  docs/user_doc/vic_app_dev/build_push_images.md
  docs/user_doc/vic_app_dev/container_operations.md
  docs/user_doc/vic_app_dev/dch_advanced.md
  docs/user_doc/vic_app_dev/dch_expand_disk.md
  docs/user_doc/vic_app_dev/dch_photon_proxy.md
  docs/user_doc/vic_app_dev/dchphoton_options.md
  docs/user_doc/vic_app_dev/deploy_multiple_docker_compose.md
  docs/user_doc/vic_app_dev/deploy_single_containervm.md
  docs/user_doc/vic_app_dev/deploy_test_dch.md
  docs/user_doc/vic_app_dev/network_use_cases.md
  docs/user_doc/vic_app_dev/photon_cert_custom.md
  docs/user_doc/vic_app_dev/photon_cert_manual.md
  docs/user_doc/vic_app_dev/putting_apps_into_production.md
  docs/user_doc/vic_app_dev/test_photon.md
  docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md
  docs/user_doc/vic_vsphere_admin/vicadmin_status_ref.md
Labels: cla-not-required

#2199 Add script bundle_dev_builds.sh for fix OVA storage path
  .drone.yml
  tests/bundle_dev_builds.sh
Labels: cla-not-required

#2195 Verify vic password during (re)initialization
  installer/build/ova-manifest.json
  installer/build/scripts/verify.py
  installer/fileserver/routes/index.go
Labels: cla-not-required

#2219 Add collect log for the missing cases
  tests/manual-test-cases/Group5-Interoperability-Tests/5-12-Multiple-VLAN.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-15-NFS-Datastore.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-16-vMotion-VCH-Appliance.robot
  tests/manual-test-cases/Group5-Interoperability-Tests/5-17-FC-Datastore.robot
  tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.3.0.robot
  tests/manual-test-cases/Group9-VIC-UI/9-2-VIC-UI-Uninstaller.robot
Labels: cla-not-required

#2215 Added step to provide password during (re)initialization
  docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
  docs/user_doc/vic_vsphere_admin/ova_reg_api.md
  docs/user_doc/vic_vsphere_admin/reinitialize_appliance.md
Labels: cla-not-required

#2224 Drop unused capabilities for containers
  installer/build/scripts/admiral/start_admiral.sh
  installer/build/scripts/vic-machine-server/vic-machine-server.service
Labels: cla-not-required

#2083 Decrease validity period for generated certificates
  installer/build/scripts/systemd/scripts/vic-appliance-tls.sh
Labels: area/security, cla-not-required, component/initialization, kind/enhancement, severity/4-minor

#2084 Disable password autocomplete during initialization
  installer/fileserver/html/index.html
Labels: area/security, component/initialization, kind/enhancement, severity/4-minor

#2221 Modify ways to identify host from css to xpath by host IP
  tests/manual-test-cases/Group5-Interoperability-Tests/5-01-Distributed-Switch-No-Cluster.robot
  tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot
Labels: cla-not-required

#2228 Update out of date build script
  installer/build/build-ova.sh
  installer/build/scripts/provisioners/provision_harbor.sh
  installer/build/scripts/upgrade/upgrade-harbor.sh
Labels: cla-not-required

#2238 fix security issue introduced by test package
  installer/fileserver/test/fixtures/index.html
  installer/fileserver/test/karma.conf.js
  installer/fileserver/test/package-lock.json
  installer/fileserver/test/package.json
  installer/fileserver/test/specs/index-handler-spec.js
Labels: cla-not-required

#2236 Fix incorrect plugin api usage
  installer/build/scripts/upgrade/upgrade.sh
  installer/fileserver/routes/plugin.go
  tests/resources/VIC-UI-Util.robot
Labels: cla-not-required

#2229 Use Harbor 1.7.0 RC1 for VIC 1.5.0
  .drone.yml
Labels: cla-not-required

#2232 Enable NTP configurable
  installer/build/bootable/config/builder.ovf
  installer/build/scripts/provisioners/system_settings.sh
  installer/build/scripts/systemd/scripts/ntp-config.sh
  installer/build/scripts/systemd/scripts/vic-appliance-environment.sh
  installer/build/scripts/systemd/units/ovf-ntp.service
  installer/build/scripts/systemd/units/vic-appliance-environment.service
  installer/build/scripts/systemd/units/vic-appliance-ready.target
  installer/ovatools/vic-ova-ui/main.go
  installer/ovatools/vic-ova-ui/network_status.go
Labels: cla-not-required

#1918 Overhaul of deployment pre-reqs and first attempt to unify the certificates doc
  docs/user_doc/SUMMARY.md
  docs/user_doc/vic_app_dev/configure_docker_client.md
  docs/user_doc/vic_cloud_admin/add_vch_fullTLS_in_portal.md
  docs/user_doc/vic_vsphere_admin/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/access_h5_ui.md
  docs/user_doc/vic_vsphere_admin/appliance_cert_reqs.md
  docs/user_doc/vic_vsphere_admin/bridge_network.md
  docs/user_doc/vic_vsphere_admin/deploy_vch.md
  docs/user_doc/vic_vsphere_admin/deploy_vch_client.md
  docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md
  docs/user_doc/vic_vsphere_admin/deploy_vch_esxi.md
  docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
  docs/user_doc/vic_vsphere_admin/graphics/appliance_certs.png
  docs/user_doc/vic_vsphere_admin/graphics/roles-certs.png
  docs/user_doc/vic_vsphere_admin/graphics/vch_certs.png
  docs/user_doc/vic_vsphere_admin/graphics/vic_certs.png
  docs/user_doc/vic_vsphere_admin/installing_vic.md
  docs/user_doc/vic_vsphere_admin/network_reqs.md
  docs/user_doc/vic_vsphere_admin/registry_cert.md
  docs/user_doc/vic_vsphere_admin/security_reference.md
  docs/user_doc/vic_vsphere_admin/tls_docker_certs.md
  docs/user_doc/vic_vsphere_admin/using_vicmachine.md
  docs/user_doc/vic_vsphere_admin/vch_admin.md
  docs/user_doc/vic_vsphere_admin/vch_cert_options.md
  docs/user_doc/vic_vsphere_admin/vch_cert_reqs.md
  docs/user_doc/vic_vsphere_admin/vch_networking.md
  docs/user_doc/vic_vsphere_admin/vch_security.md
  docs/user_doc/vic_vsphere_admin/vi_reqs.md
  docs/user_doc/vic_vsphere_admin/vic_cert_reference.md
  docs/user_doc/vic_vsphere_admin/vic_cert_use.md
  docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md
Labels: area/pub, cla-not-required

#2241 Small fixes caused by merge
  docs/user_doc/vic_vsphere_admin/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/vi_reqs.md
Labels: cla-not-required

#2233 Added vicpassword to OVA registration API doc
  docs/user_doc/vic_vsphere_admin/ova_reg_api.md
Labels: area/pub, cla-not-required

#2226 Documented that appliance password is limited to 30 chars
  docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
Labels: area/pub, cla-not-required

#2246 Fixing base href
  index.html
Labels: cla-not-required

#2235 Doc update for upgrade to 1.5.0
  docs/user_doc/SUMMARY.md
  docs/user_doc/vic_cloud_admin/logging_in_MP.md
  docs/user_doc/vic_vsphere_admin/SUMMARY.md
  docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
  docs/user_doc/vic_vsphere_admin/ova_reg_api.md
  docs/user_doc/vic_vsphere_admin/uninstall_vic.md
  docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
  docs/user_doc/vic_vsphere_admin/upgrade_appliance_manual.md
  docs/user_doc/vic_vsphere_admin/upgrade_vch.md
  docs/user_doc/vic_vsphere_admin/upgrading_vic.md
Labels: area/pub, cla-not-required

#2243 Add vic root password into interactive mode
  installer/build/scripts/upgrade/upgrade.sh
Labels: cla-not-required

#2239 Redirect / to Admiral UI
  installer/build/scripts/provisioners/provision_harbor.sh
Labels: cla-not-required

#2254 Update Harbor GA build
  .drone.yml
Labels: cla-not-required

#2255 Pack dev version of Admiral
  .drone.yml
Labels: cla-not-required

#2218 Specified that all VIC engine components run Photon OS 2.0, updated dch-photon version.
  docs/user_doc/vic_app_dev/build_push_images.md
  docs/user_doc/vic_app_dev/dch_expand_disk.md
  docs/user_doc/vic_app_dev/dch_photon_proxy.md
  docs/user_doc/vic_app_dev/dchphoton_options.md
  docs/user_doc/vic_app_dev/photon_cert_custom.md
  docs/user_doc/vic_app_dev/photon_cert_manual.md
  docs/user_doc/vic_app_dev/test_photon.md
  docs/user_doc/vic_overview/intro_to_vic_engine.md
  docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md
  docs/user_doc/vic_vsphere_admin/ts_recover_password.md
  docs/user_doc/vic_vsphere_admin/vch_install_packages.md
  docs/user_doc/vic_vsphere_admin/vch_mount_nfsshare.md
  docs/user_doc/vic_vsphere_admin/vic_engine_bundle.md
Labels: area/pub, cla-not-required

#2261 Change vic-product CI run as sequential
  .drone.yml
  tests/wait_until_previous_builds_complete.sh
Labels: cla-not-required

#2273 remove $ in nginx config of harbor
  installer/build/scripts/provisioners/provision_harbor.sh
Labels: cla-not-required
